# -*- coding: utf-8 -*-
"""Statistic_Learning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZrVihO-85XH_1Raf1NgWjxWTe6tXjCZ
"""

import numpy as np
import pandas as pd
import io

# 畫圖用的套件
import matplotlib.pyplot as plt  
import seaborn as sns

# 讀取 Google Drive 的資料
from google.colab import drive 
drive.mount('/content/gdrive')

# Load the data
data=pd.read_csv('/content/gdrive/My Drive/統計學習/heart.csv')
data.head()

# Summary of Data
data.describe()

sns.countplot(x="target", data=data, palette="RdBu")
data.target.value_counts()

# Correlection Matrix
Corr = data.corr()
plt.figure(figsize=(10, 10))
sns.heatmap(Corr, cmap = 'Blues',annot = True,fmt='.2f')
plt.title ("Correlation Matrix",fontsize = 14)
data.corr().target

# Pairplot
sns.pairplot(data, kind="scatter", hue="target", markers=["o", "s"], palette="Set2")
plt.show()

sns.countplot(data['sex'],hue = data['target'],palette="RdBu")
plt.xlabel("Sex (0 = female, 1= male)")
plt.legend(["Not Disease", "Disease"])

fig, axes = plt.subplots(nrows=1, ncols=2,figsize=(10, 4))


Disease = 'Disease'
Not_Disease= 'Not Disease'


Female = data[data['sex']==0]
Male = data[data['sex']==1]

ax = sns.distplot(Female[Female['target']==0].age.dropna(), bins=18, label = Not_Disease, ax = axes[0], kde =False)
ax = sns.distplot(Female[Female['target']==1].age.dropna(), bins=18, label = Disease, ax = axes[0], kde =False)

ax.legend()
ax.set_title('Female')

ax = sns.distplot(Male[Male['target']==0].age.dropna(), bins=18, label = Not_Disease, ax = axes[1], kde =False)
ax = sns.distplot(Male[Male ['target']==1].age.dropna(), bins=18, label = Disease, ax = axes[1], kde =False)

ax.legend()
ax.set_title('Male')

Disease = 'Disease'
Not_Disease= 'Not Disease'


ax = sns.scatterplot(x= data.age[data.target==1],y=data.thalach[(data.target==1)], label = Disease)
ax = sns.scatterplot(x= data.age[data.target==0],y=data.thalach[(data.target==0)], label = Not_Disease)
ax.legend()
plt.ylabel("Maximum Heart Rate")

ax = sns.countplot(x='cp', data=data, hue='target',palette="RdBu")
ax.set_xticklabels(['Typical Angina', 'Atypical Angina', 'Non-anginal Pain', 'Asymptomatic']);
ax.set_title('Disease vs. Chest Pain Type')
plt.ylabel('count')
plt.xlabel('')

plt.legend(['Not Disease', 'Disease']);

ax = sns.countplot(x='exang', data=data, hue='target',palette="RdBu")
plt.legend(['Not Disease', 'Disease']);

# Covariance Matrix
cov = data.cov()
plt.figure(figsize=(10, 10))
sns.heatmap(cov, cmap = 'Blues',annot = True,fmt='.2f')
plt.title ("Covariance Matrix",fontsize = 14)
